### ISSUE TITLE
Blacklist should not relaunch the app

### ISSUE THREAD

**Issue by rudametw** [bmhagui/stage_52#10]
Blacklisting should not ask questions like 1 to add new window, 0 to XX.

Furthermore, blacklisting should not relaunch a new power_up instance. If I'm already running power_up in another terminal than MAYBE it should restart the process (signal no_hup ?) to load the new configuration. That would be more usable.

**Comment by bmhagui** [comment]
If I don't ask then I would only be able to add one application to the black list when I use the flag? 

There is no need to re-start the application because the black-list is updated with every iteration of the application, so the new configuration is taken into consideration.

What if the application is not already running?  If I don't launch it directly after, then when I launch it manually the configuration would not be taken into consideration since the black_list_pid.conf file is wiped clean upon every first start-up of the application, this is done since it has old PIDS of the last time it was running.

Might find a solution through /proc pseudo file system, to be continued..
